# Keiba AI Configuration File

# Data Scraping Settings
scraping:
  start_year: 2024
  end_year: 2024
  max_workers: 3
  timeout: 120
  retry_count: 3
  output_format: xlsx  # xlsx or csv

# Data Encoding Settings
encoding:
  input_dir: data
  output_dir: encoded
  config_dir: config

# Model Training Settings
model:
  test_size: 0.2
  random_state: 42
  n_trials: 100  # Number of Optuna optimization trials
  cv_folds: 5    # Number of cross-validation folds
  
  # LightGBM Default Parameters
  lgb_params:
    objective: binary
    metric: auc
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    verbose: -1
    random_state: 42

# Backtesting Settings
backtest:
  initial_capital: 1000000
  betting_fraction: 0.005  # Kelly criterion base (0.5%)
  monthly_stop_loss: 0.1   # 10% monthly stop loss
  ev_threshold: 1.2        # Expected value threshold
  confidence_threshold: 0.7 # Minimum confidence for betting

# Output Settings
output:
  model_dir: models
  results_dir: results
  log_level: INFO

# Feature Engineering Settings
features:
  use_past_races: 5  # Number of past races to consider
  use_seasonal: true
  use_jockey_stats: true
  use_trainer_stats: true
  use_horse_stats: true